name: build tags

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o bin/teslamatebackup main.go

      - uses: actions/upload-artifact@v2
        with:
          name: teslamatebackup
          path: bin/teslamatebackup
